packages:
  # all packages in direct subdirs of packages/
  - 'packages/*'
  # exclude packages that are inside test directories
  - '!**/test/**'

catalog:
  '@types/react': '^18.3.3'
  '@types/react-dom': '^18.3.0'
  '@vitejs/plugin-react': '^5.1.1'
  eslint: ^9.20.1
  openai: ^4.76.0
  react: ^18.3.1
  react-dom: ^18.3.1
  'styled-components': '^6.1.19'
  tsx: ^4.19.2
  typescript: ^5.7.3
  vite: ^6.3.5
  vite-tsconfig-paths: ^5.1.4
