import { Recipe } from '../types/Recipe';

export const recipes: Recipe[] = [
  {
    id: 'simple-mango-lassi',
    title: 'Simple Mango Lassi',
    imageUrl: '/images/recipes/mangoLassi.png',
    description:
      'A refreshing and creamy mango yogurt drink, perfect for a hot day or as a sweet treat.',
    prepTime: '5 minutes',
    servings: '1-2',
    ingredients: [
      { name: 'frozen mango cubes', amount: '1.5 cups' },
      { name: 'plain yogurt', amount: '1 cup' },
      { name: 'milk', amount: '½ cup' },
      { name: 'sugar, honey, or agave', amount: '1-2 tbsp' },
      { name: 'salt', amount: 'a small pinch' },
      { name: 'vanilla extract', amount: 'a few drops' },
      { name: 'ice cubes', amount: 'optional' },
    ],
    instructions: [
      'Thaw mango slightly (optional): Let the frozen cubes sit for 5-10 minutes so they blend smoother.',
      'Blend: Add mango, yogurt, milk, sweetener, salt, and vanilla (if using) into a blender.',
      'Blend until smooth: Add more milk if you want it thinner, or more mango/yogurt if you want it thicker.',
      'Taste and adjust: Add extra sweetness or a splash more milk if needed.',
      'Serve immediately: Pour into a chilled glass.',
    ],
  },
  {
    id: 'quick-bulgogi',
    title: 'Quick Bulgogi',
    imageUrl: '/images/recipes/quickBulgogi.png',
    description:
      'A fast and flavorful Korean beef dish made with thinly sliced marinated beef, perfect for a weeknight dinner.',
    prepTime: '10 minutes',
    cookTime: '10 minutes',
    servings: '2-3',
    ingredients: [
      { name: 'thinly sliced beef', amount: '~1 lb' },
      { name: 'soy sauce', amount: '3 tbsp' },
      { name: 'sugar or honey', amount: '1 tbsp' },
      { name: 'sesame oil', amount: '1 tbsp' },
      { name: 'minced garlic', amount: '2 tsp' },
      { name: 'minced ginger', amount: '1 tsp' },
      { name: 'mirin', amount: '1 tbsp' },
      { name: 'onion', amount: '½ small' },
      { name: 'green onion', amount: '1' },
      { name: 'pear or apple', amount: '½ small' },
      { name: 'sesame seeds', amount: 'for garnish' },
    ],
    instructions: [
      'Marinate: In a bowl, mix soy sauce, sugar, sesame oil, garlic, ginger, mirin, and grated pear/apple. Add beef and sliced onion + green onion. Mix well. Let it sit for 10-15 minutes (or overnight for deeper flavor).',
      "Cook: Heat a pan or skillet over medium-high heat. Add the beef mixture (no need for extra oil if it's fatty). Stir-fry for 5-7 minutes until browned and caramelized.",
      'Finish: Sprinkle sesame seeds and a drizzle of sesame oil before serving.',
      'Serve with steamed rice, kimchi, and lettuce leaves for wraps (ssam style).',
      'You can also toss it into fried rice or top it on noodles for a fast meal.',
    ],
  },
  {
    id: 'cajun-salmon',
    title: 'Cajun Salmon',
    imageUrl: '/images/recipes/cajunSalmon.png',
    description:
      'A simple but incredible Cajun salmon recipe that hits all the right notes - smoky, spicy, buttery, and juicy inside with a perfect crust.',
    prepTime: '10 minutes',
    cookTime: '15 minutes',
    servings: '2-4',
    ingredients: [
      { name: 'salmon fillets', amount: '2 (6-8 oz each)' },
      { name: 'Cajun seasoning', amount: '1½ tbsp' },
      { name: 'olive oil', amount: '1 tbsp' },
      { name: 'butter', amount: '1 tbsp' },
      { name: 'garlic', amount: '2 cloves' },
      { name: 'lemon juice', amount: '1 tsp' },
      { name: 'parsley or green onion', amount: 'optional, for garnish' },
    ],
    instructions: [
      'Pat the salmon dry. This helps get a good sear. Then rub olive oil over both sides.',
      'Coat with seasoning. Sprinkle Cajun seasoning evenly and press it in lightly.',
      'Sear the salmon. Heat a skillet over medium-high heat. Once hot, add butter. When melted and sizzling, add the salmon (skin side down if using skin). Cook 4-5 minutes per side, depending on thickness, until it flakes easily and develops a golden crust.',
      'Add garlic and lemon. In the last 30 seconds, toss minced garlic into the butter in the pan. Sauté just until fragrant, then drizzle lemon juice over the salmon.',
      'Rest and serve. Garnish with chopped parsley or green onions. Serve with lemon wedges.',
    ],
  },
];
